--- 
$schemaver: 1.1
name: byu-wso2-request
type: Library
aliases:
short_description: utility for making a server to server request using ws02 authentication
assignment_group: gro:AD-Academic Information Management
notes: 
maintained_by:
  - martingarn
developed_by_byu: True
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: https://github.com/byu-oit-appdev/byu-wso2-request
  source_repo_url: https://github.com/byu-oit-appdev/byu-wso2-request
  swagger_urls:
microservice: False
technologies_used:
  - JavaScript
stages:
  production:
    urls:
      product_page: https://github.com/byu-oit-appdev/byu-wso2-request
      physical_url: 
      virtual_url: 
    hosting_location: 
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
      supports:
        software:
        service:
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: confidential
  env: prd
  app: byu-wso2-request
  team: gro:AD-Academic Information Management
federation_json_url: https://raw.githubusercontent.com/byu-oit-appdev/byu-wso2-request/master/.repo-meta.yml

